import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync, spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const tool = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const nativeRoot = process.env.REFERENCE_NATIVE_ROOT || path.resolve(tool, '../..');
const nativeSearch = [nativeRoot,...(fs.existsSync(path.join(tool,'config.json'))?JSON.parse(fs.readFileSync(path.join(tool,'config.json'))).parserSearch||[]:[]).map(p=>path.resolve(nativeRoot,p))];
const fixture = () => {
 const root = fs.mkdtempSync(path.join(os.tmpdir(), 'building-reference-test-'));
 fs.mkdirSync(path.join(root, 'src')); fs.mkdirSync(path.join(root, 'tools/building-reference'), {recursive:true});
 for (const name of ['core.mjs','cli.mjs','run.mjs','watch.mjs']) if(fs.existsSync(path.join(tool,name))) fs.copyFileSync(path.join(tool,name),path.join(root,'tools/building-reference',name));
 fs.writeFileSync(path.join(root,'src/model.ts'), 'export interface Task { id: string; title: string }\nexport function done(task: Task): boolean { return false }\nexport const secret = "DO_NOT_EXPORT_THIS_SECRET";\n');
 fs.writeFileSync(path.join(root,'src/view.ts'), 'import type { Task } from "./model"; export const view = (task: Task) => task.title;\n');
 fs.writeFileSync(path.join(root,'package.json'),'{}');
 fs.writeFileSync(path.join(root,'tools/building-reference/config.json'), JSON.stringify({repository:'test/local',defaultBranch:'main',adapter:'typescript',scopes:['src'],excludeSegments:[],supporting:[],parserSearch:nativeSearch,planned:[],limits:['Runtime behavior not validated']}));
 spawnSync('git',['init','-b','main'],{cwd:root}); spawnSync('git',['add','.'],{cwd:root});spawnSync('git',['-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-m','synthetic'],{cwd:root});
 return root;
};
const call = (root, cmd) => spawnSync(process.execPath,[path.join(root,'tools/building-reference/cli.mjs'),cmd],{cwd:root,encoding:'utf8'});
const accept = root => {const p=call(root,'inspect');assert.equal(p.status,0,p.stderr);const data=JSON.parse(p.stdout);fs.writeFileSync(path.join(root,'tools/building-reference/mapping.json'),JSON.stringify({review:'synthetic test fixture',sources:data.sources},null,2));return data;};
const ready = root => {accept(root);const p=call(root,'generate');assert.equal(p.status,0,p.stderr);assert.equal(call(root,'check').status,0);};
const json = (root,name) => JSON.parse(fs.readFileSync(path.join(root,'docs/building-reference',name),'utf8'));
const cleanup = root => fs.rmSync(root,{recursive:true,force:true});
// Break caught: parser executes constants or omits actual declared fields/imports.
test('source parsing lists literal vocabulary without executing or exporting initializers',()=>{const r=fixture();try {const d=accept(r);assert.deepEqual(d.sources['src/model.ts'].exports.map(x=>x.name),['Task','done','secret']);assert.deepEqual(d.sources['src/model.ts'].exports[0].members,['id','title']);assert.equal(d.sources['src/view.ts'].imports[0],'./model');assert.ok(!JSON.stringify(d).includes('DO_NOT_EXPORT_THIS_SECRET'));}finally{cleanup(r);}});
// Break caught: output timestamp or ignored self-output causes a non-deterministic regeneration loop.
test('repeat generation is deterministic and does not rewrite identical bytes',()=>{const r=fixture();try{ready(r);const p=path.join(r,'docs/building-reference/index.html'),bytes=fs.readFileSync(p),stamp=fs.statSync(p).mtimeMs;assert.equal(call(r,'generate').status,0);assert.deepEqual(fs.readFileSync(p),bytes);assert.equal(fs.statSync(p).mtimeMs,stamp);}finally{cleanup(r);}});
// Break caught: normal body/comment changes leave stale input identity or false clean Git claims.
test('ordinary dirty body edit refreshes input digest without inventing semantics',()=>{const r=fixture();try{ready(r);const before=json(r,'provenance.json').inputDigest;fs.appendFileSync(path.join(r,'src/model.ts'),'// ordinary edit\n');assert.notEqual(call(r,'check').status,0);assert.equal(call(r,'generate').status,0);const p=json(r,'provenance.json');assert.notEqual(p.inputDigest,before);assert.ok(p.git.dirtyPaths.includes('src/model.ts'));assert.equal(call(r,'check').status,0);}finally{cleanup(r);}});
// Break caught: auto approval of field additions, missing input, syntax error, new file.
for(const [name,mutate] of [['new public field',r=>fs.writeFileSync(path.join(r,'src/model.ts'),'export interface Task { id: string; title: string; completed: boolean }')],['missing source',r=>fs.unlinkSync(path.join(r,'src/view.ts'))],['unsupported syntax',r=>fs.writeFileSync(path.join(r,'src/model.ts'),'export interface {')],['new inventory input',r=>fs.writeFileSync(path.join(r,'src/new.ts'),'export const newThing = 1;')]]) test(name+' fails visibly stale and repaired reviewed mapping recovers',()=>{const r=fixture();try{ready(r);mutate(r);const p=call(r,'generate');assert.notEqual(p.status,0);assert.match(fs.readFileSync(path.join(r,'docs/building-reference/index.html'),'utf8'),/STALE/);assert.notEqual(call(r,'check').status,0);if(name==='unsupported syntax')fs.writeFileSync(path.join(r,'src/model.ts'),'export interface Task { id: string; title: string }');accept(r);assert.equal(call(r,'generate').status,0);assert.equal(call(r,'check').status,0);}finally{cleanup(r);}});
// Break caught: checker trusts sidecar banner instead of deriving output independently.
test('output and provenance tampering fail independent checking',()=>{const r=fixture();try{ready(r);fs.appendFileSync(path.join(r,'docs/building-reference/map.json'),' ');assert.notEqual(call(r,'check').status,0);assert.equal(call(r,'generate').status,0);const p=json(r,'provenance.json');p.git.head='forged';fs.writeFileSync(path.join(r,'docs/building-reference/provenance.json'),JSON.stringify(p));assert.notEqual(call(r,'check').status,0);}finally{cleanup(r);}});
// Break caught: two simultaneous writers claim ready or one deletes another lock.
test('existing writer lock rejects contention and is preserved',()=>{const r=fixture();try{ready(r);const lock=path.join(r,'tools/building-reference/.writer-lock');fs.mkdirSync(lock);fs.writeFileSync(path.join(lock,'owner.json'),JSON.stringify({pid:process.pid}));assert.notEqual(call(r,'generate').status,0);assert.ok(fs.existsSync(lock));fs.rmSync(lock,{recursive:true});assert.equal(call(r,'generate').status,0);}finally{cleanup(r);}});
// Break caught: literal local source links are absent or runtime interpreted as proof.
test('generated guide provides encoded source links and honest planned and scope boundaries',()=>{const r=fixture();try{ready(r);const h=fs.readFileSync(path.join(r,'docs/building-reference/index.html'),'utf8');assert.ok(h.includes('../../src/model.ts'));assert.match(h,/Future scope is not mapped/);assert.match(h,/Runtime behavior not validated/);assert.match(h,/candidate/);}finally{cleanup(r);}});
// Break caught: Git-only attribution changes accepted without recomputation.
test('Git-only branch switch invalidates provenance and checked recovery records new branch',()=>{const r=fixture();try{ready(r);spawnSync('git',['switch','-c','other'],{cwd:r});assert.notEqual(call(r,'check').status,0);assert.equal(call(r,'generate').status,0);assert.equal(json(r,'provenance.json').git.branch,'other');}finally{cleanup(r);}});
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const stopOwned = async child => {if(!child||child.exitCode!==null||child.signalCode!==null)return;const exited=new Promise(resolve=>child.once('exit',resolve));child.kill('SIGTERM');await Promise.race([exited,delay(3000)]);if(child.exitCode===null&&child.signalCode===null)child.kill('SIGKILL');};

const until=async check=>{for(let i=0;i<80;i++){if(check())return;await delay(50);}throw Error('Timed out waiting for reference lifecycle');};
// Break caught: watch wrapper starts more than one writer, misses pending changes, or leaves owned child alive.
test('owned dev lifecycle coalesces edit and shuts down only its child with original arguments',async()=>{const r=fixture();let child;try{const c=JSON.parse(fs.readFileSync(path.join(r,'tools/building-reference/config.json')));c.commands={'root:dev':{command:'node child.cjs',cwd:'.',watch:true}};fs.writeFileSync(path.join(r,'tools/building-reference/config.json'),JSON.stringify(c));fs.writeFileSync(path.join(r,'child.cjs'),'require("fs").writeFileSync("child.json",JSON.stringify({pid:process.pid,args:process.argv.slice(2)}));setInterval(()=>{},1000);');ready(r);child=spawn(process.execPath,[path.join(r,'tools/building-reference/run.mjs'),'root:dev','--port','3211'],{cwd:r,stdio:'ignore'});await until(()=>fs.existsSync(path.join(r,'child.json')));const owned=JSON.parse(fs.readFileSync(path.join(r,'child.json')));assert.deepEqual(owned.args,['--port','3211']);const before=json(r,'provenance.json').inputDigest;fs.appendFileSync(path.join(r,'src/model.ts'),'\n// pending one\n');fs.appendFileSync(path.join(r,'src/model.ts'),'// pending two\n');await until(()=>{try{return json(r,'provenance.json').inputDigest!==before&&call(r,'check').status===0}catch{return false}});child.kill('SIGTERM');await new Promise(resolve=>child.once('exit',resolve));await until(()=>{try{process.kill(owned.pid,0);return false}catch{return true}});assert.ok(!fs.existsSync(path.join(r,'tools/building-reference/.writer-lock')));}finally{await stopOwned(child);for(const file of ['child.json','sub/nested.json']){const p=path.join(r,file);if(fs.existsSync(p)){try{process.kill(JSON.parse(fs.readFileSync(p)).pid,'SIGTERM')}catch{}}}cleanup(r);}});
// Break caught: build hooks generate dirty outputs before native clean-candidate checks.
test('native clean phase executes original command and leaves reference bytes untouched',()=>{const r=fixture();try{const c=JSON.parse(fs.readFileSync(path.join(r,'tools/building-reference/config.json')));c.commands={'root:build':{command:'node -e "require(\'fs\').writeFileSync(\'native-ran\',\'yes\')"',cwd:'.',watch:false}};fs.writeFileSync(path.join(r,'tools/building-reference/config.json'),JSON.stringify(c));ready(r);const before=fs.readFileSync(path.join(r,'docs/building-reference/index.html'));fs.appendFileSync(path.join(r,'src/model.ts'),'// native phase input drift');const p=spawnSync(process.execPath,[path.join(r,'tools/building-reference/run.mjs'),'root:build'],{cwd:r,env:{...process.env,BUILDING_REFERENCE_NATIVE_PHASE:'1'}});assert.equal(p.status,0);assert.equal(fs.readFileSync(path.join(r,'native-ran'),'utf8'),'yes');assert.deepEqual(fs.readFileSync(path.join(r,'docs/building-reference/index.html')),before);assert.notEqual(call(r,'check').status,0);}finally{cleanup(r);}});
// Break caught: publication ignores a source race and leaves a mixed ready bundle.
test('source changes during generation yield coherent latest output or visible stale with recovery',async()=>{const r=fixture();try{ready(r);const child=spawn(process.execPath,[path.join(r,'tools/building-reference/cli.mjs'),'generate'],{cwd:r,stdio:'ignore'});let n=0;const timer=setInterval(()=>fs.appendFileSync(path.join(r,'src/model.ts'),'// race '+n+++'\n'),2);await new Promise(resolve=>child.once('exit',resolve));clearInterval(timer);const result=call(r,'check');if(result.status!==0){assert.equal(call(r,'generate').status,0);}assert.equal(call(r,'check').status,0);}finally{cleanup(r);}});
// Break caught: a generic upkeep diagram is presented as the application connection map.
test('guide draws an actual declared local connection with linked source endpoints',()=>{const r=fixture();try{ready(r);const h=fs.readFileSync(path.join(r,'docs/building-reference/index.html'),'utf8');assert.match(h,/aria-label="Actual source module connection"/);assert.match(h,/<svg[\s\S]*src\/view.ts[\s\S]*src\/model.ts/);}finally{cleanup(r);}});
// Break caught: unsupported declaration silently disappears from reviewed public vocabulary.
test('native-valid but unsupported public declaration fails closed',()=>{const r=fixture();try{ready(r);fs.appendFileSync(path.join(r,'src/model.ts'),'\nexport import Unmapped = require("library");\n');assert.notEqual(call(r,'generate').status,0);assert.match(fs.readFileSync(path.join(r,'docs/building-reference/index.html'),'utf8'),/STALE/);}finally{cleanup(r);}});
// Break caught: native TSX vocabulary in legacy .ts is silently excluded or treated as native runtime proof.
test('legacy TS filename with JSX parses explicitly as source grammar without native compatibility claim',()=>{const r=fixture();try{fs.writeFileSync(path.join(r,'src/model.ts'),'export function View() { return <span>value</span>; }');const d=accept(r);assert.equal(d.sources['src/model.ts'].grammar,'TSX grammar in .ts; native filename/runtime compatibility unverified');assert.deepEqual(d.sources['src/model.ts'].exports.map(x=>x.name),['View']);assert.equal(call(r,'generate').status,0);}finally{cleanup(r);}});
// Break caught: a reviewed absent initial scope later gains source invisibly.
test('reviewed initially absent scope is explicit and new input still requires review',()=>{const r=fixture();try{const p=path.join(r,'tools/building-reference/config.json'),c=JSON.parse(fs.readFileSync(p));c.scopes.push('future');c.absentScopes=['future'];fs.writeFileSync(p,JSON.stringify(c));ready(r);fs.mkdirSync(path.join(r,'future'));fs.writeFileSync(path.join(r,'future/new.ts'),'export const thing=1;');assert.notEqual(call(r,'generate').status,0);assert.match(fs.readFileSync(path.join(r,'docs/building-reference/index.html'),'utf8'),/STALE/);}finally{cleanup(r);}});
// Break caught: stale is visible but hides candidate byte identity and points historical evidence to current files.
test('stale page shows candidate identity and retains separately named historical evidence',()=>{const r=fixture();try{ready(r);fs.writeFileSync(path.join(r,'src/model.ts'),'export interface Task { newField: number }');assert.notEqual(call(r,'generate').status,0);const state=json(r,'state.json');assert.equal(state.state,'stale');assert.ok(state.candidate.inputDigest);assert.match(fs.readFileSync(path.join(r,'docs/building-reference/index.html'),'utf8'),/Candidate input digest/);const old=fs.readFileSync(path.join(r,'docs/building-reference/historical.html'),'utf8');assert.match(old,/HISTORICAL SNAPSHOT/);assert.ok(old.includes('historical-provenance.json'));assert.ok(fs.existsSync(path.join(r,'docs/building-reference/historical-map.json')));}finally{cleanup(r);}});
// Break caught: AST is parsed from old bytes but provenance captures new bytes before publication recheck.
test('an edit between source parsing and hashing cannot bind old vocabulary to new input bytes',()=>{const r=fixture();try{ready(r);const hook=path.join(r,'race-hook.cjs');fs.writeFileSync(hook,'const fs=require("node:fs"),old=fs.readFileSync;let changed=false;fs.readFileSync=function(file,...args){const out=old.call(this,file,...args);if(!changed&&String(file).endsWith("src/model.ts")){changed=true;fs.writeFileSync(file,"export interface Task { id: string; freshUnreviewed: boolean }\\n");}return out;};');const p=spawnSync(process.execPath,['--require',hook,path.join(r,'tools/building-reference/cli.mjs'),'generate'],{cwd:r,encoding:'utf8'});assert.notEqual(p.status,0,'must reject old AST/new-byte attribution');assert.match(fs.readFileSync(path.join(r,'docs/building-reference/index.html'),'utf8'),/STALE/);assert.notEqual(call(r,'check').status,0);}finally{cleanup(r);}});
// Break caught: a long-running production start defers refresh until it exits instead of at startup.
test('non-watching native start refreshes before launching its original child',()=>{const r=fixture();try{const c=JSON.parse(fs.readFileSync(path.join(r,'tools/building-reference/config.json')));c.commands={'root:start':{command:'node startup-child.cjs',cwd:'.',watch:false,startup:true}};fs.writeFileSync(path.join(r,'tools/building-reference/config.json'),JSON.stringify(c));fs.writeFileSync(path.join(r,'startup-child.cjs'),'const cp=require("node:child_process"),fs=require("node:fs");fs.writeFileSync("startup-status",String(cp.spawnSync(process.execPath,["tools/building-reference/cli.mjs","check"]).status));');ready(r);fs.appendFileSync(path.join(r,'src/model.ts'),'// startup edit');const p=spawnSync(process.execPath,[path.join(r,'tools/building-reference/run.mjs'),'root:start'],{cwd:r,encoding:'utf8'});assert.equal(p.status,0,p.stderr);assert.equal(fs.readFileSync(path.join(r,'startup-status'),'utf8'),'0');assert.ok(!fs.existsSync(path.join(r,'tools/building-reference/.watch-lock')));}finally{cleanup(r);}});
// Break caught: declared readonly/generic/defaulted parameter contracts change without review.
test('explicit public readonly and generic constraints fail pending review',()=>{const r=fixture();try{fs.writeFileSync(path.join(r,'src/model.ts'),'export interface Task<T> { id: T }');ready(r);fs.writeFileSync(path.join(r,'src/model.ts'),'export interface Task<T extends string> { readonly id: T }');assert.notEqual(call(r,'generate').status,0);assert.match(fs.readFileSync(path.join(r,'docs/building-reference/index.html'),'utf8'),/STALE/);}finally{cleanup(r);}});
// Break caught: destructuring/computed declarations copy initializer values into the map.
test('destructured defaults and computed names never disclose initializer values',()=>{const r=fixture();try{fs.writeFileSync(path.join(r,'src/model.ts'),'export const { token = "SECRET_DESTRUCTURED_VALUE" } = {}; export class Task { ["SECRET_COMPUTED_VALUE" + "suffix"](): void {} }');const d=accept(r);assert.ok(!JSON.stringify(d).includes('SECRET_DESTRUCTURED_VALUE'));assert.ok(!JSON.stringify(d).includes('SECRET_COMPUTED_VALUE'));assert.ok(d.sources['src/model.ts'].exports.some(x=>x.name.includes('token')));}finally{cleanup(r);}});
// Break caught: nested workspace launch starts competing writers or loses arguments/cwd; shutdown drops pending changes.
test('nested workspace lifecycle uses one writer and reconciles pending shutdown edits',async()=>{const r=fixture();let child;try{fs.mkdirSync(path.join(r,'sub'));const c=JSON.parse(fs.readFileSync(path.join(r,'tools/building-reference/config.json')));c.commands={'root:dev':{command:'node tools/building-reference/run.mjs sub:dev',cwd:'.',watch:true},'sub:dev':{command:'node child.cjs',cwd:'sub',watch:true}};fs.writeFileSync(path.join(r,'tools/building-reference/config.json'),JSON.stringify(c));fs.writeFileSync(path.join(r,'sub/child.cjs'),'const fs=require("node:fs");fs.writeFileSync("nested.json",JSON.stringify({pid:process.pid,args:process.argv.slice(2),cwd:process.cwd(),marker:process.env.REFERENCE_TEST_MARKER}));setInterval(()=>{},1000);');ready(r);child=spawn(process.execPath,[path.join(r,'tools/building-reference/run.mjs'),'root:dev','--port','4444'],{cwd:r,env:{...process.env,REFERENCE_TEST_MARKER:'kept'},stdio:'ignore'});await until(()=>fs.existsSync(path.join(r,'sub/nested.json')));const native=JSON.parse(fs.readFileSync(path.join(r,'sub/nested.json')));assert.deepEqual(native.args,['--port','4444']);assert.equal(native.cwd,fs.realpathSync(path.join(r,'sub')));assert.equal(native.marker,'kept');assert.equal(JSON.parse(fs.readFileSync(path.join(r,'tools/building-reference/.watch-lock/owner.json'))).pid,child.pid);fs.appendFileSync(path.join(r,'src/model.ts'),'// shutdown pending change');child.kill('SIGTERM');await new Promise(resolve=>child.once('exit',resolve));await until(()=>{try{process.kill(native.pid,0);return false}catch{return true}});assert.equal(call(r,'check').status,0);assert.ok(!fs.existsSync(path.join(r,'tools/building-reference/.watch-lock')));}finally{await stopOwned(child);for(const file of ['child.json','sub/nested.json']){const p=path.join(r,file);if(fs.existsSync(p)){try{process.kill(JSON.parse(fs.readFileSync(p)).pid,'SIGTERM')}catch{}}}cleanup(r);}});

// Review regression: lossy quoted keys/type literal normalization collapses different public contracts.
for(const [label,before,after] of [
 ['quoted property key',`export interface Task { "a'b": string }`,`export interface Task { "ab": string }`],
 ['literal whitespace',`export type Mode = "a b";`,`export type Mode = "ab";`],
 ['literal slash comments',`export type Mode = "http://a";`,`export type Mode = "http://b";`],
 ['literal block comments',`export type Mode = "/*a*/";`,`export type Mode = "/*b*/";`]
])test('reviewed '+label+' mutation fails pending deliberate recovery',()=>{const r=fixture();try{fs.writeFileSync(path.join(r,'src/model.ts'),before);ready(r);fs.writeFileSync(path.join(r,'src/model.ts'),after);assert.notEqual(call(r,'generate').status,0,'different public literal/key must not match old mapping');assert.notEqual(call(r,'check').status,0);accept(r);assert.equal(call(r,'generate').status,0);assert.equal(call(r,'check').status,0);}finally{cleanup(r);}});

// Review regression: independent sibling launches need one shared updater, then live takeover.
test('independent sibling dev launchers preserve both apps and transfer updater ownership',async()=>{const r=fixture();const children=[];try{for(const sub of ['one','two'])fs.mkdirSync(path.join(r,sub));const c=JSON.parse(fs.readFileSync(path.join(r,'tools/building-reference/config.json')));c.commands={'one:dev':{command:'node child.cjs',cwd:'one',watch:true},'two:dev':{command:'node child.cjs',cwd:'two',watch:true}};fs.writeFileSync(path.join(r,'tools/building-reference/config.json'),JSON.stringify(c));for(const sub of ['one','two'])fs.writeFileSync(path.join(r,sub,'child.cjs'),'const fs=require("node:fs");fs.writeFileSync("native.json",JSON.stringify({pid:process.pid,args:process.argv.slice(2),cwd:process.cwd(),marker:process.env.REFERENCE_TEST_MARKER}));setInterval(()=>{},1000);');ready(r);const launch=(key,port)=>{const child=spawn(process.execPath,[path.join(r,'tools/building-reference/run.mjs'),key,'--port',port],{cwd:r,env:{...process.env,REFERENCE_TEST_MARKER:key,BUILDING_REFERENCE_PARENT:''},stdio:'ignore'});children.push(child);return child;};const first=launch('one:dev','3333');await until(()=>fs.existsSync(path.join(r,'one/native.json')));const second=launch('two:dev','4444');await until(()=>fs.existsSync(path.join(r,'two/native.json')));for(const [sub,key,port] of [['one','one:dev','3333'],['two','two:dev','4444']]){const native=JSON.parse(fs.readFileSync(path.join(r,sub,'native.json')));assert.deepEqual(native.args,['--port',port]);assert.equal(native.cwd,fs.realpathSync(path.join(r,sub)));assert.equal(native.marker,key);}const lock=path.join(r,'tools/building-reference/.watch-lock/owner.json');assert.equal(JSON.parse(fs.readFileSync(lock)).pid,first.pid);const exited=new Promise(resolve=>first.once('exit',resolve));first.kill('SIGTERM');await exited;await until(()=>{try{return JSON.parse(fs.readFileSync(lock)).pid===second.pid}catch{return false}});const nativeTwo=JSON.parse(fs.readFileSync(path.join(r,'two/native.json')));process.kill(nativeTwo.pid,0);const before=json(r,'provenance.json').inputDigest;fs.appendFileSync(path.join(r,'src/model.ts'),'// sibling takeover edit');await until(()=>{try{return json(r,'provenance.json').inputDigest!==before&&call(r,'check').status===0}catch{return false}});const finished=new Promise(resolve=>second.once('exit',resolve));second.kill('SIGTERM');await finished;assert.ok(!fs.existsSync(path.join(r,'tools/building-reference/.watch-lock')));assert.ok(!fs.existsSync(path.join(r,'tools/building-reference/.writer-lock')));}finally{for(const child of children)await stopOwned(child);for(const sub of ['one','two']){const f=path.join(r,sub,'native.json');if(fs.existsSync(f)){try{process.kill(JSON.parse(fs.readFileSync(f)).pid,'SIGTERM')}catch{}}}cleanup(r);}});

// Review regression: actual Expo platform launchers must use the reviewed reference lifecycle.
if(fs.existsSync(path.join(tool,'config.json'))&&JSON.parse(fs.readFileSync(path.join(tool,'config.json'))).repository==='SabineMR/freedom-petition')test('actual reviewed Expo android and ios launchers retain flags and use upkeep',()=>{const c=JSON.parse(fs.readFileSync(path.join(tool,'config.json'))),pkg=JSON.parse(fs.readFileSync(path.resolve(tool,'../../package.json')));for(const platform of ['android','ios']){assert.equal(pkg.scripts[platform],'node tools/building-reference/run.mjs root:'+platform);assert.equal(c.commands['root:'+platform].command,'expo start --'+platform+' --port 1234');assert.equal(c.commands['root:'+platform].cwd,'.');assert.equal(c.commands['root:'+platform].watch,true);}});

// Review recovery: a stopped updater's immutable lease is reclaimed without blocking a live sibling app.
test('a stopped updater is recovered while live ownership and native sibling are preserved',async()=>{const r=fixture();let holder,child;try{const c=JSON.parse(fs.readFileSync(path.join(r,'tools/building-reference/config.json')));c.commands={'root:dev':{command:'node child.cjs',cwd:'.',watch:true}};fs.writeFileSync(path.join(r,'tools/building-reference/config.json'),JSON.stringify(c));fs.writeFileSync(path.join(r,'child.cjs'),'const fs=require("node:fs");fs.writeFileSync("native.json",JSON.stringify({pid:process.pid}));setInterval(()=>{},1000);');fs.writeFileSync(path.join(r,'holder.mjs'),'import fs from "node:fs";import {WatchLease} from "./tools/building-reference/watch.mjs";const lease=new WatchLease(process.cwd());if(!lease.claim())process.exit(1);fs.writeFileSync("holder.json",JSON.stringify({pid:process.pid}));setInterval(()=>{},1000);');ready(r);holder=spawn(process.execPath,[path.join(r,'holder.mjs')],{cwd:r,stdio:'ignore'});await until(()=>fs.existsSync(path.join(r,'holder.json')));child=spawn(process.execPath,[path.join(r,'tools/building-reference/run.mjs'),'root:dev'],{cwd:r,env:{...process.env,BUILDING_REFERENCE_PARENT:''},stdio:'ignore'});await until(()=>fs.existsSync(path.join(r,'native.json')));const owner=path.join(r,'tools/building-reference/.watch-lock/owner.json');assert.equal(JSON.parse(fs.readFileSync(owner)).pid,holder.pid,'live owner is retained');const before=json(r,'provenance.json').inputDigest;fs.appendFileSync(path.join(r,'src/model.ts'),'// abandoned owner pending edit');const exited=new Promise(resolve=>holder.once('exit',resolve));holder.kill('SIGTERM');await exited;await until(()=>{try{return JSON.parse(fs.readFileSync(owner)).pid===child.pid&&json(r,'provenance.json').inputDigest!==before&&call(r,'check').status===0}catch{return false}});process.kill(JSON.parse(fs.readFileSync(path.join(r,'native.json'))).pid,0);const nativePid=JSON.parse(fs.readFileSync(path.join(r,'native.json'))).pid;await stopOwned(child);await until(()=>{try{process.kill(nativePid,0);return false}catch{return true}});assert.ok(!fs.existsSync(path.join(r,'tools/building-reference/.watch-lock')));}finally{await stopOwned(holder);await stopOwned(child);const f=path.join(r,'native.json');if(fs.existsSync(f)){try{process.kill(JSON.parse(fs.readFileSync(f)).pid,'SIGTERM')}catch{}}cleanup(r);}});

if(fs.existsSync(path.join(tool,'config.json'))&&JSON.parse(fs.readFileSync(path.join(tool,'config.json'))).repository==='SabineMR/freedom-petition')test('reviewed Expo launchers forward original platform port args and environment to a synthetic CLI',async()=>{const reviewed=JSON.parse(fs.readFileSync(path.join(tool,'config.json')));for(const platform of ['android','ios']){const r=fixture();let child;try{const c=JSON.parse(fs.readFileSync(path.join(r,'tools/building-reference/config.json')));c.commands={['root:'+platform]:reviewed.commands['root:'+platform]};fs.writeFileSync(path.join(r,'tools/building-reference/config.json'),JSON.stringify(c));const bin=path.join(r,'fake-bin');fs.mkdirSync(bin);fs.writeFileSync(path.join(bin,'expo'),'#!/usr/bin/env node\nconst fs=require("node:fs");fs.writeFileSync("expo.json",JSON.stringify({pid:process.pid,args:process.argv.slice(2),cwd:process.cwd(),marker:process.env.REFERENCE_TEST_MARKER}));setInterval(()=>{},1000);',{mode:0o755});ready(r);child=spawn(process.execPath,[path.join(r,'tools/building-reference/run.mjs'),'root:'+platform,'--offline'],{cwd:r,env:{...process.env,PATH:bin+path.delimiter+process.env.PATH,REFERENCE_TEST_MARKER:'kept-'+platform,BUILDING_REFERENCE_PARENT:''},stdio:'ignore'});await until(()=>fs.existsSync(path.join(r,'expo.json')));const native=JSON.parse(fs.readFileSync(path.join(r,'expo.json')));assert.deepEqual(native.args,['start','--'+platform,'--port','1234','--offline']);assert.equal(native.cwd,fs.realpathSync(r));assert.equal(native.marker,'kept-'+platform);fs.appendFileSync(path.join(r,'src/model.ts'),'// platform pending edit');await stopOwned(child);assert.equal(call(r,'check').status,0);await until(()=>{try{process.kill(native.pid,0);return false}catch{return true}});assert.ok(!fs.existsSync(path.join(r,'tools/building-reference/.watch-lock')));}finally{await stopOwned(child);const f=path.join(r,'expo.json');if(fs.existsSync(f)){try{process.kill(JSON.parse(fs.readFileSync(f)).pid,'SIGTERM')}catch{}}cleanup(r);}}});
